config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hesab.urls'))
]

hesab/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('weeklist/', views.WeekList.as_view(), name='week_list'),
    # path('<int:pk>/weekdetails/', views.WeekDetails.as_view(), name='week_details'),
    path('<int:pk>/refresh/', views.refresh, name='refresh'),
]

hesab/models.py
from django.db import models
from django.contrib.auth.models import User


class Week(models.Model):
    name = models.CharField(max_length=100)
    date_create = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Shopping(models.Model):
    CHOICES = (('0', 'شنبه'),
               ('1', 'یکشنبه'),
               ('2', 'دوشنبه'),
               ('3', 'سه شنبه'),
               ('4', 'چهارشنبه'),
               ('5', 'پنج شنبه'),
               ('6', 'جمعه')
               )

    name = models.CharField(choices=CHOICES, max_length=100)
    week = models.ForeignKey(Week, on_delete=models.PROTECT, related_name='weekshopping', null=True)
    day = models.DateField()
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usershopping')
    consumer = models.ManyToManyField(User)
    amount = models.IntegerField()
    goods = models.CharField(max_length=500)

    def __str__(self):
        return f'{self.day} | {self.buyer}'


class Money(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usermoney')
    week = models.ForeignKey(Week, on_delete=models.CASCADE, related_name='weekmoney')
    money = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user} | {self.week} | {0 if self.money==0 else self.money}'

hesab/forms.py
from django import forms

from .models import Week, Shopping, Money


class MoneyForm(forms.Form):
    # class Meta:
    #     model = Money
    #     fields = ['user', 'week', 'money']

    user = forms.Select()
    week = forms.Select()
    money = forms.IntegerField()

hesab/views.py
from django.shortcuts import render, reverse
from django.views import generic
from django.contrib.auth.models import User

from .models import Week, Shopping, Money
from .forms import MoneyForm


class WeekList(generic.ListView):
    model = Week
    template_name = 'hesab/week_list.html'
    context_object_name = 'week_list'


def refresh(request,pk):
    week = Week.objects.get(id=pk)
    shopping = Shopping.objects.filter(week=week).order_by('name')
    moneys = Money.objects.filter(week=week)
    # print(moneys)
    for money in moneys:
        print('=')
        my_money = 0
        chosen_shopping = Shopping.objects.filter(week=week)
        chosen_shopping_buyer = Shopping.objects.filter(week=week, buyer=money.user)
        for shop in chosen_shopping_buyer:
            my_money += int(shop.amount)
        sum=0
        for shop in chosen_shopping:
            sum += shop.amount
            numbers = shop.consumer.all().count()
            # print((shop.consumer.all()))
            if money.user in shop.consumer.all():
                my_money -= int(shop.amount / numbers)
            Money.objects.filter(user=money.user, week=week).update(money=my_money)
    return render(request, 'hesab/week_details.html', {'week': week,'sum':sum,'shopping':shopping})






















# class WeekDetails(generic.DetailView):
#     model = Week
#     template_name = 'hesab/week_details.html'
#     context_object_name = 'week'
#
#
# def refresh2(request, pk):
#     week = Week.objects.get(id=pk)
#     shopping = Shopping.objects.filter(week=week)
#     moneys = Money.objects.filter(week=week)
#     for shop in shopping:
#         numbers = shop.consumer.all().count()
#         for con in shop.consumer.all():
#             print(con)
#             my_money = 0
#             my_money -= int(shop.amount/numbers)
#             print('money : ' ,my_money , )
#             if shop.buyer == con:
#                 print(con)
#                 print(shop.buyer == con)
#                 my_money += int(shop.amount)
#             me = Money.objects.filter(user=con, week=week).update(money=my_money)
#             print('me money :',me,'000')
#             # my_con =con
#             print('-------------------------------------------')
#     print('=====================================================')
#             # me_2 = Money.objects.update_or_create(user=my_con
#             #                                       ,week=week,money=10)
#             # money_form = MoneyForm()
#             # print(me_2)
#             # me2 = me.objects.update(money=my_money)
#     return render(request, 'hesab/week_details.html', {'week': week})

hesab/templates/hesab/week_details.html
{% extends '_base.html' %}

{% block title %}
    Week Details
{% endblock title %}

{% block extra %}
    <p  class="btn btn-danger">جمع کل : {{ sum }}</p>
{% endblock extra%}

{% block content %}
    <div class="container mt-4">
        <div class="row">
        <a class="btn btn-warning" type="submit" href="{% url 'refresh' week.id %}">@ Refresh</a>
            <div class="col-9">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col"> روز</th>
                        <th scope="col">خریدار</th>
                        <th scope="col">مبلغ</th>
                        <th scope="col">افراد</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for day in shopping%}
                            <th scope="row">{{ day.get_name_display }}</th>
                            <td>{{ day.buyer }}</td>
                            <td>{{ day.amount }}</td>


                            <td>
                                {% for con in day.consumer.all %}
                                    <span style="color:red"> | </span> {{ con.username }}
                                {% endfor %}
                            </td>

                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-3">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">نام</th>
                        <th scope="col">اعتبار</th>
{#                        <th scope="col">Last</th>#}
{#                        <th scope="col">Handle</th>#}
                    </tr>
                    </thead>
                    <tbody>
                        {% for mon in week.weekmoney.all %}
                    <tr>
                            <th scope="row">{{ mon.user }}</th>
                            <td>
                            {% if mon.money == 0 %}
                                0
                            {% else %}
                                {{ mon.money }}
                            {% endif %}
                            </td>


                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

{% endblock content %}

hesab/templates/hesab/week_list.html
{% extends '_base.html' %}

{% block title %}

{% endblock title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            {% for week in week_list %}
                <div class="col-9">
                    <div class="card shadow-sm my-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ week.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted small py-2">{{ week.date_create }}</h6>
                            <p class="card-text py-3">
                                {{ week.weekshopping.all }}
                            </p>
                            <a class="btn btn-sm btn-success" href="{% url 'refresh' week.id %}">Read More
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-3">

                <div class="card my-4">
                    <h5 class="card-header">About</h5>
                    <div class="card-body">
                        <p class="card-text">We love python and django. So we created a blog site to share our
                            thoughts</p>
                        <a href="#"
                           class="btn btn-sm btn-danger">
                            More...
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">CodingYar.com</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
                <a class="nav-link" href="#">Blog</a>
            </div>
        </div>
        <div class="mx-2 text-white">Welcome</div>
    </div>
</nav>

<div class="container-fluid bg-info">
    <div class="row py-3">
        <div class="col-md-8 col-md-10 mx-auto">
            <h3 class="my-4 mt-3 text-white">Welcome to  Blog</h3>
            {% block extra %}

            {% endblock extra %}

        </div>
    </div>
</div>


{% block content %}

{% endblock content %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>